# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        MainWindow.setMinimumSize(QtCore.QSize(640, 480))
        MainWindow.setMaximumSize(QtCore.QSize(640, 480))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 640, 480))
        self.tabWidget.setMinimumSize(QtCore.QSize(640, 480))
        self.tabWidget.setMaximumSize(QtCore.QSize(640, 480))
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.tabWidget.addTab(self.tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayoutWidget = QtWidgets.QWidget(self.tab_2)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(30, 30, 491, 151))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_source = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_source.setText("")
        self.lineEdit_source.setReadOnly(True)
        self.lineEdit_source.setObjectName("lineEdit_source")
        self.gridLayout.addWidget(self.lineEdit_source, 0, 1, 1, 1)
        self.pushButton_albums = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_albums.setObjectName("pushButton_albums")
        self.gridLayout.addWidget(self.pushButton_albums, 1, 2, 1, 1)
        self.lineEdit_cdnUrl = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_cdnUrl.setObjectName("lineEdit_cdnUrl")
        self.gridLayout.addWidget(self.lineEdit_cdnUrl, 2, 1, 1, 1)
        self.label_cdnUrl = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_cdnUrl.setObjectName("label_cdnUrl")
        self.gridLayout.addWidget(self.label_cdnUrl, 2, 0, 1, 1)
        self.lineEdit_albums = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_albums.setReadOnly(True)
        self.lineEdit_albums.setObjectName("lineEdit_albums")
        self.gridLayout.addWidget(self.lineEdit_albums, 1, 1, 1, 1)
        self.label_albums = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_albums.setObjectName("label_albums")
        self.gridLayout.addWidget(self.label_albums, 1, 0, 1, 1)
        self.label_source = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_source.setObjectName("label_source")
        self.gridLayout.addWidget(self.label_source, 0, 0, 1, 1)
        self.pushButton_source = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_source.setObjectName("pushButton_source")
        self.gridLayout.addWidget(self.pushButton_source, 0, 2, 1, 1)
        self.pushButton_gen = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_gen.setGeometry(QtCore.QRect(530, 40, 71, 31))
        self.pushButton_gen.setObjectName("pushButton_gen")
        self.pushButton_output = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_output.setGeometry(QtCore.QRect(530, 120, 71, 61))
        self.pushButton_output.setObjectName("pushButton_output")
        self.console = QtWidgets.QTextBrowser(self.tab_2)
        self.console.setGeometry(QtCore.QRect(30, 200, 571, 229))
        self.console.setMinimumSize(QtCore.QSize(571, 229))
        self.console.setMaximumSize(QtCore.QSize(571, 229))
        self.console.setObjectName("console")
        self.pushButton_import = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_import.setEnabled(False)
        self.pushButton_import.setGeometry(QtCore.QRect(530, 80, 71, 31))
        self.pushButton_import.setObjectName("pushButton_import")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.textEdit = QtWidgets.QTextEdit(self.tab_3)
        self.textEdit.setGeometry(QtCore.QRect(0, 0, 631, 441))
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.tabWidget.addTab(self.tab_3, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "yunの相册生成工具"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("MainWindow", "欢迎"))
        self.pushButton_albums.setText(_translate("MainWindow", "打开文件夹"))
        self.label_cdnUrl.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">cdnUrl:</span></p></body></html>"))
        self.label_albums.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">albums:</span></p></body></html>"))
        self.label_source.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">source:</span></p></body></html>"))
        self.pushButton_source.setText(_translate("MainWindow", "打开文件夹"))
        self.pushButton_gen.setText(_translate("MainWindow", "生成"))
        self.pushButton_output.setText(_translate("MainWindow", "导出"))
        self.pushButton_import.setText(_translate("MainWindow", "导入"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "生成相册"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Hexo-yun相册生成工具</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">使用方法</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">1) source: 博客的相册路径source/albums</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">2) albums: 相册albums主目录(该目录下是以文件夹为单位的相册集)</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">3) 设置cdnUrl链接前缀(cdn采用jsdelivr)</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">4) 生成:  生成文件BOM</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">5) 导入: 单独生成或更新md</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">5) 导出: 生成md</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">注意事项</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">1) 相册生成不支持设置密码，请到相册页手动开启</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">2）新建相册随机选取封面，示例：</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">    </span><span style=\" font-size:12pt; color:#a9b7c6;\">index.md</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'JetBrains Mono\',\'monospace\'; font-size:13.5pt; color:#cc7832;\">    - </span><span style=\" font-family:\'JetBrains Mono\',\'monospace\'; font-size:13.5pt; color:#a9b7c6;\">caption: None<br />      url: /albums/test.html<br />      cover: https://cdn.jsdelivr.net/gh/Sknp1006/cdn@master/img/albums/test/008.png<br />      desc: None</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">3) 点击生成后会验证cdnUrl是否合法(需联网)，验证albums_path与cdnUrl是否匹配</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Hexo-yun: </span><a href=\"https://github.com/YunYouJun/hexo-theme-yun\"><span style=\" font-size:12pt; text-decoration: underline; color:#0000ff;\">https://github.com/YunYouJun/hexo-theme-yun</span></a></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">文章链接: </span><a href=\"https://sknplz.xyz/2020/08/12/albums_creater/\"><span style=\" font-size:12pt; text-decoration: underline; color:#0000ff;\">https://sknplz.xyz/2020/08/12/albums_creater/</span></a></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt; text-decoration: underline; color:#0000ff;\"><br /></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "帮助"))
